---
default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: development
